/******************************************************************************
 * Discord Character Overlay Generator
 * build.js
 *
 * CSS Builder
 ******************************************************************************/

import { getPlayers } from "./player.js";
import { GITHUB } from "./config.js";

/*=============================================================================
    Build CSS
=============================================================================*/

export async function buildCSS() {

    const sections = [

        buildHeader(),

        await buildVariables(),

        await buildLayout(),

        await buildCharacter(),

        await buildAnimation(),

        await buildName(),

        await buildMute(),

        await buildTheme(),

        buildPlayerRules(),

        buildFooter()

    ];

    return sections.join("\n\n");

}

/*=============================================================================
    Header
=============================================================================*/

function buildHeader() {

    return `/*==================================================

Discord Character Overlay

Generated by Discord Character Overlay Generator

==================================================*/`;

}

/*=============================================================================
    Variables
=============================================================================*/

async function buildVariables() {

    return await loadCss("../overlay/variables.css");

}

async function buildLayout() {

    return await loadCss("../overlay/layout.css");

}

async function buildCharacter() {

    return await loadCss("../overlay/character.css");

}

async function buildAnimation() {

    return await loadCss("../overlay/animation.css");

}

async function buildName() {

    return await loadCss("../overlay/name.css");

}

async function buildMute() {

    return await loadCss("../overlay/mute.css");

}

async function buildTheme() {

    return await loadCss("../overlay/theme.css");

}

/******************************************************************************
    CSS Loader
******************************************************************************/

async function loadCss(path){

    const response = await fetch(path);

    if(!response.ok){

        throw new Error(`${path} の読み込みに失敗しました`);

    }

    return await response.text();

}

/*=============================================================================
    Player Rules
=============================================================================*/

function buildPlayerRules() {

    const players = getPlayers();

    let css = "";

    players.forEach(player => {

        css += createPlayerRule(player);

    });

    return css;

}

function createPlayerRule(player){

    const imageUrl = createImageUrl(player);

    return `

img[src*="${escapeCSS(player.discordId)}"]{

    content:url("${imageUrl}");

}

`;

}

function createImageUrl(player){

    return `${GITHUB.RAW_ROOT}/${player.gameId}/${player.characterId}.png`;

}

/*=============================================================================
    Footer
=============================================================================*/

function buildFooter(){

    return `

/*==================================================

End Of File

==================================================*/`;

}

/*=============================================================================
    Escape
=============================================================================*/

function escapeCSS(value){

    return String(value)

        .replace(/\\/g,"\\\\")

        .replace(/"/g,'\\"');

}