/******************************************************************************
 * Discord Character Overlay Generator
 * build.js
 *
 * CSS Builder
 ******************************************************************************/

import { getPlayers } from "./player.js";
import { GITHUB } from "./config.js";
import { getGames } from "./game.js";


/*=============================================================================
    Build CSS
=============================================================================*/

/**
 * Overlay用CSSを生成する
 *
 * @returns {Promise<string>}
 */
export async function buildCSS() {

    const sections = [

        buildHeader(),

        await buildVariables(),

        await buildTheme(),

        await buildLayout(),

        await buildCharacter(),

        await buildAnimation(),

        await buildName(),

        await buildMute(),

        await buildPlayerRules(),

        buildFooter()

    ];

    return sections.join("\n\n");

}


/*=============================================================================
    Header
=============================================================================*/

/**
 * 生成CSSのヘッダーを作成する
 *
 * @returns {string}
 */
function buildHeader() {

    return `/*==================================================

Discord Character Overlay

Generated by Discord Character Overlay Generator

==================================================*/`;

}


/*=============================================================================
    Overlay CSS
=============================================================================*/

async function buildVariables() {

    return await loadCss(
        "../overlay/core/variables.css"
    );

}


async function buildTheme() {

    return await loadCss(
        "../overlay/core/theme.css"
    );

}


async function buildLayout() {

    return await loadCss(
        "../overlay/core/layout.css"
    );

}


async function buildCharacter() {

    return await loadCss(
        "../overlay/modules/character.css"
    );

}


async function buildAnimation() {

    return await loadCss(
        "../overlay/core/animation.css"
    );

}


async function buildName() {

    return await loadCss(
        "../overlay/modules/name.css"
    );

}


async function buildMute() {

    return await loadCss(
        "../overlay/modules/mute.css"
    );

}


/*=============================================================================
    CSS Loader
=============================================================================*/

/**
 * CSSファイルを読み込む
 *
 * @param {string} path
 * @returns {Promise<string>}
 */
async function loadCss(path) {

    const response =
        await fetch(path);

    if (!response.ok) {

        throw new Error(
            `CSSファイルの読み込みに失敗しました: ${path} (${response.status})`
        );

    }

    return await response.text();

}


/*=============================================================================
    Player Rules
=============================================================================*/

/**
 * 登録プレイヤーごとのCSSを生成する
 *
 * @returns {Promise<string>}
 */
async function buildPlayerRules() {

    const players =
        getPlayers();

    const rules =
        await Promise.all(
            players.map(
                player =>
                    createPlayerRule(player)
            )
        );

    return rules.join("\n\n");

}


/**
 * プレイヤー1人分のCSSを生成する
 *
 * @param {Object} player
 * @returns {Promise<string>}
 */
async function createPlayerRule(player) {

    const imageUrl =
        createImageUrl(player);

    const imageDataUrl =
        await imageUrlToDataUrl(
            imageUrl
        );

    return `
.voice_state[data-userid="${escapeCSS(player.discordId)}"] {

    --dco-character-image:
        url("${imageDataUrl}");

    --dco-character-scale:1;

    --dco-character-offset-x:0px;

    --dco-character-offset-y:0px;

    --dco-character-flip:1;

}`;

}


/*=============================================================================
    Image URL
=============================================================================*/

/**
 * プレイヤー画像のGitHub RAW URLを生成する
 *
 * @param {Object} player
 * @returns {string}
 */
function createImageUrl(player) {

    const games =
        getGames();

    const game =
        games.find(
            item => item.id === player.gameId
        );

    if (!game) {

        throw new Error(
            `ゲームが見つかりません: ${player.gameId}`
        );

    }

    const character =
        game.characters.find(
            item => item.id === player.characterId
        );

    if (!character) {

        throw new Error(
            `キャラクターが見つかりません: ${player.characterId}`
        );

    }

    return (
        `${GITHUB.RAW_ROOT}/` +
        `${game.folder}/` +
        `${character.image}`
    );

}


/*=============================================================================
    Image Data URL
=============================================================================*/

/**
 * 画像URLをData URIへ変換する
 *
 * @param {string} url
 * @returns {Promise<string>}
 */
async function imageUrlToDataUrl(url) {

    const response =
        await fetch(url);

    if (!response.ok) {

        throw new Error(
            `画像の読み込みに失敗しました: ${url} (${response.status})`
        );

    }

    const blob =
        await response.blob();

    return await blobToDataUrl(
        blob
    );

}


/**
 * BlobをData URIへ変換する
 *
 * @param {Blob} blob
 * @returns {Promise<string>}
 */
function blobToDataUrl(blob) {

    return new Promise(
        (resolve, reject) => {

            const reader =
                new FileReader();

            reader.onload =
                () => {

                    resolve(
                        reader.result
                    );

                };

            reader.onerror =
                () => {

                    reject(
                        reader.error
                    );

                };

            reader.readAsDataURL(
                blob
            );

        }
    );

}


/*=============================================================================
    Footer
=============================================================================*/

/**
 * 生成CSSのフッターを作成する
 *
 * @returns {string}
 */
function buildFooter() {

    return `/*==================================================

End Of File

==================================================*/`;

}


/*=============================================================================
    Escape
=============================================================================*/

/**
 * CSS文字列用に値をエスケープする
 *
 * @param {*} value
 * @returns {string}
 */
function escapeCSS(value) {

    return String(value)

        .replace(
            /\\/g,
            "\\\\"
        )

        .replace(
            /"/g,
            '\\"'
        );

}